### PR TITLE
[Fix #290] Also count exceptions

### LINKED ISSUE #290: Eastwood doesn't report Exceptions when exceptions are thrown during analysis
```✔ ~/Documents/github.com/baz
21:46 $ lein eastwood
== Eastwood 0.3.0 Clojure 1.8.0 JVM 1.8.0_172
Directories scanned for source files:
  src test
== Linting baz.core ==
Exception thrown during phase :analyze+eval of linting namespace baz.core

The following form was being processed during the exception:
(/ 1 0)


Shown again with metadata for debugging (some metadata elided for brevity):
^{:line 4} (/ 1 0)


An exception was thrown while analyzing namespace baz.core
Lint results may be incomplete.  If there are compilation errors in
your code, try fixing those.  If not, check above for info on the
exception.
== Linting baz.core-test ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
```

One would expect `Exceptions thrown` to be 1

### PR DESCRIPTION
**Pull request by slipset**

### CODE REVIEW

**Comment by slipset** [comment]
@noisesmith does this solve the problem for you?

**Comment by noisesmith** [comment]
checking this now, thanks for the quick turn around on this!

**Comment by noisesmith** [comment]
yes, this does address the issue! I'll be using this version as soon as it goes live, thanks again

**Comment by jafingerhut** [comment]
Glad you got the user feedback you were looking for.  The change appears reasonable to me, but haven't tested it myself or thought through the possible execution paths that might lead to it.  But its only possible effect is pretty clearly only in the value of the number printed in the summary line.

**Comment by noisesmith** [comment]
also, importantly, changes a successful return code to an error code, which is important in my project's CI flow

**Pull request merged**
