### PR TITLE
Support for custom linters

### PR DESCRIPTION
**Pull request by MatthewDarling**
## What's this thing?

This PR allows Eastwood to load arbitrary linters from files in a project. Anyone using Eastwood can extend it with linters that are specific to their project, dev team, etc. Library authors could distribute Eastwood linters to their users as a set of guidelines.

Lots of cool options opened up by this :)

## How would it be used?

**Step one**, write some linters using `tools.analyzer`. Just to keep things organized, imagine a directory `linters` containing the files `company_styleguide.clj` and `security_practices.clj`.

**Step two**, within those files, call the new `add-linter` API referring to each of your new linters:

```clojure
(defn style-linter1 [analyze-results opts]
  ... )

(add-linter
  {:name style-linter1
   :fn style-linter1})

(defn style-linter2 [analyze-results opts]
  ... )

(add-linter
  {:name style-linter2
   :fn style-linter2})
```

 Any linters added by calling `add-linter` API will be added automatically to every invocation of Eastwood.

**Step three**, configure the new `:lint-files` option:

```clojure
{:eastwood {;;; existing Eastwood options
            :lint-files ["linters/company_styleguide.clj" "linters/security_practices.clj"]
            ;;; ... other options etc ... }
```

These files are loaded with `io/reader` like the existing `:config-files` option. Paths are relative to the project root directory.

And that's it!

## Technical details

`eastwood.util/add-linter` is an analogue to `eastwood.util/disable-warning`. The `:lint-files` are arbitrary Clojure files evaluated in the context of `eastwood.util`, similar to the existing `:config-files` option. Custom linter functions receive the same arguments as existing built-in lint functions.

In terms of the implementation, there's not much more to it - given the existing features of Eastwood, it was pretty clear how to add this :)

## Things to finalize

1. Need a new name for the `add-linter` API - I only just noticed it conflicts with the existing `:add-linter` configuration option for off-by-default linters built-in to Eastwood.
2. It would be good to have a story for third party libraries to distribute linters to their users. I *think* `io/reader` can load files from the resources of your dependencies, so in theory a project could just refer to those somehow. Imagine the Datomic client library containing Eastwood linters which provide linters that point out bad practices and inefficient ways of doing things.
3. If third party libraries can distribute linters, they should have globally unique linter names. It would be good for Eastwood to check for linter name uniqueness, and at least warn users when they've got a name conflict. Even better if they could be uniquefied automatically, but let's not get ahead of ourselves :)
4. Consider whether custom linters should be able to be turned off. Linters specific to a project probably don't need to be turned off by configuration (just comment out the call to `add-linter`), but if they're from some dependency of yours, you might want a bit more control.
5. Add more documentation to the README, and possibly elsewhere in the project. #182 specifically asked for documentation on how to do this, so even though I wrote the feature, I can't claim to have resolve that issue, haha. I know at least the "Last options map adjustments" section needs adjustment.

### CODE REVIEW

**Comment by jafingerhut** [comment]
Interesting.

I don't spend a lot of time on Eastwood these days, but if you are interested in becoming a contributor to Eastwood, and for bonus points even take on some of these tasks:

+ test these changes on the 'crucible' set of tests, to make sure that these changes do not make things worse on that set of projects, comparing results before and after these changes.  I can give instructions on how to run them if it isn't easy to determine from the existing files, but start by reading crucible/README.txt to see if it makes sense.
+ write up a bit of documentation to add to a section of the README somewhere, perhaps with a sample project on Github demonstrating a simple use of the feature.

Then I could spend a few hours doing some level of code review and asking questions about your implementation.

**Comment by MatthewDarling** [comment]
I'm definitely willing to contribute documentation alongside the code :)

----------

In terms of running Crucible, what I did was set my `~/.lein/profiles.clj` to this:

```clojure
{:user
 {:plugins [[jonase/eastwood "0.2.5"]]}}
```

Then run this:

```bash
cd crucible
git checkout master
./lint.sh >& out_master.txt
git checkout support-for-custom-linters
./lint.sh >& out.txt
```

Is that the general idea?

Without having added any custom linters, there didn't seem to be interesting changes in the output of `crucible/lint.sh`. Most of the changes were stuff like memory addresses.

One thing I did see was off-by-one changes in column numbers where reflection warnings were reported. Mostly related to Seesaw calling `getSize`, also a big block from `src/examples/clojure/clojure/test/array_test.clj`. Is that something that typically varies?

**Comment by jafingerhut** [comment]
That is definitely the general idea.  Memory addresses changing is definitely normal, and I have also seen but have no explanation for off-by-one changes in column numbers for reflection warnings.  I've just never dug into it, as it doesn't seem terribly significant.  It might be nice to eliminate those differences in the future, and/or find a way to post-process the output to make it quicker to diff outputs, but I've found using a tool like 'ediff' in Emacs, or similar tools, I can scan through the differences I don't care about fairly quickly, so it hasn't been a big enough pain point on time to do something more about yet.

What I mainly pay attention to are new linter warnings that show up for the same code, or that no longer appear for the same code.  If you don't see any of that happening, then things sound good.

**Comment by jafingerhut** [comment]
If you think everything is ready to go other than documentation, let me know and I will try to find some time to read through the changes more carefully in the next couple of weeks.  I wouldn't recommend writing up any detailed documentation until the code changes are in, in case some of the details change before then.

**Comment by MatthewDarling** [comment]
Yep, there weren't any new/removed lint warnings in the Crucible tests when I ran them.

I put together [a sample project](https://github.com/MatthewDarling/clj-custom-linters-example) to test running custom lints from command line, since I'd been running them from the REPL previously. Everything worked just the same as in the REPL, which was wonderful :)

It's also a quick draft of some user-facing documentation.

**Comment by MatthewDarling** [comment]
Got the branch synced to `master` to get rid of the merge conflicts. Diff looks okay to my eyes, don't think anything weird snuck into the merge :)

**Comment by slipset** [comment]
@MatthewDarling Hi, sorry to be jumping in so late in the game. I'd really be interested in incorporating this PR, but there are a couple of things I'd like to investigate before merging.
First of all, I think I'd like to set up a protocol for a linter. Reason for this is that I was working a bit on the deprecated-linter, and stuff seems a bit tangled up. I think it would be really nice for third-party linter implementators to have a somewhat clear API to code against.
Unfortunately I haven't spent time on looking into this protocol yet.

Also, before committing to an external API for Eastwood, I'd like to investigate the possibility of running linters in parallell. Again, I haven't thought this through yet, but I'd like to do that before committing to an api.

I guess we could accommodate your PR and wanting to do a protocol based API by putting your `add-linter` function in an `...alpha...` ns which would indicate that the API can/will change.

Thoughts?

**Comment by slipset** [comment]
And having written that, if you want to chime in to the discussion of how such a protocol would look, I'd be very happy.

**Comment by MatthewDarling** [comment]
I'll admit that I haven't reviewed all the existing linter implementations. It seemed like their implementations were all quite different, so I'd bet they offer a lot of good inspiration for what the protocol needs to do :)

When I was writing my [example custom linters](https://github.com/MatthewDarling/clj-custom-linters-example/tree/master/linters), I cribbed from some of the simpler Eastwood linters. They followed this pattern:

  1. Filter the provided AST to find relevant expressions
  2. Iterate over the filtered collection, applying some arbitrary code that may return a lint failure
      * I used the `for` macro + `:when` to iterate and "return nothing" for some items, but an API where functions return `nil` for no failures or 1+ failure maps would be fine too
  3. Retrieve the `:var` and `:env` for the expression to have the right metadata for `util/add-loc-info`
  4. Construct a (hopefully) clear message about the issue

Based on that, here's a protocol that I think could reimplement my two examples:

```clojure
(defprotocol Linter
  (linter-name
    [linter]
    "Returns the linter name as a keyword.") ;;;assume this is used for both naming the linter and in the lint results
  (relevant-exprs
    [linter analyze-results opts]
    "Returns the exprs in `analyze-results` which should be linted.")
  (lint-expr
    [linter expr opts]
    "Lint `expr`. Valid return values: `nil`, lint result map like {:linter :foo :msg 'blah'}, string lint
    message, or collection of string lint messages/result maps."))
```

What I had in mind here was to be as flexible as possible. Important points:

  * Assume that `add-loc-info` will be called within Eastwood
  * `linter-name` can be used by Eastwood to turn a string into `{:name (linter-name linter) :msg (lint-expr ... )}`
  * `relevant-exprs` can use `opts` to influence its behaviour (disable the check, lint-specific filters, etc)
  * `relevant-exprs` operates on the entire `analyze-results`, rather than a single AST node, in case multiple nodes are needed for a given lint check. It might be possible for the argument to be a single node if `tools.analyzer` has nice tree navigation functions
  * `lint-expr` can use `opts` to influence its behaviour (disable the check, configuration for reporting, configuration of strictness, etc)
  * `lint-expr` can return a lot of different stuff:
      * `nil` if `expr` passes the lint check
      * a plain string as the `:msg` for the check
      * a result map with both `:linter` and `:msg`, useful if a given linter may return different values for the `:linter` key
      * a collection of strings
      * a collection of maps

The main downside to using a protocol is that you need to use something like `defrecord` to provide your "linter" to Eastwood. I guess it could allow something fancy like a stateful linter... But I don't know if Eastwood has enough guarantees about execution order to make that reliable.

At least, it might be nice to offer a helper macro which takes a map of functions and turns it into a `defrecord`.

----------

Here's a vague, untested prototype of what the Eastwood code to use that protocol looks like in my head:

```clojure
(defn- normalize-linter-result
  "Ensure that `lint-result` is a map with keys `:name`, `:msg`, and
  has `loc-info` attached."
  [linter expr lint-result]
  (as-> lint-result $
    (if-not (string? $)
      $
      {:name (linter-name linter) :msg $})
    (if (has-loc-info? $)
      $
      (eastwood.util/add-loc-info (:env expr) $))))

(defn- normalize-all-linter-results
  "Ensure that lint-result is a set of lint result maps."
  [linter expr lint-result]
  (as-> lint-result $
    (if (and (coll? $) (not (map? $)))
      (map #(normalize-linter-result linter expr %) $)
      (hash-set (normalize-linter-result linter expr $)))
    (set $)))

(for [linter (concat eastwood-linters (find-custom-linters ...))
        analyzed-ns (analyze-all-ns ...)]
  (mapcat #(normalize-all-linter-results (lint-expr linter % opts)) (relevant-exprs linter analyzed-ns opts)))
```

The `normalize` stuff is painful, but it gives a lot of flexibility to lint implementations, which seems like a decent reason to have some ugly internal details.

**Comment by slipset** [comment]
Sorry for making your life hard with conflicts.

But, I've added a branch https://github.com/slipset/eastwood/tree/add-ilint-portocol where I play with a protocol, so you can have a look

**Comment by vemv** [comment]
Indeed creating an ILint protocol should be the way to go. https://github.com/slipset/eastwood/tree/add-ilint-portocol doesn't apply to `master` as it's been a few years but anyone reapplying that work would be welcome to open a PR.

I'll close this PR in the meantime. @MatthewDarling , I hope you still give the linter some use :) the ecosystem has changed quite rapidly. However Eastwood remains a uniquely accurate proposition providing some distinct insights.

**Pull request closed without merging**
