### PR TITLE
Add middleware to store eastwood options in namespace var

### PR DESCRIPTION
**Pull request by venantius**
This commit adds leiningen middleware to store the project's
eastwood options in `eastwood.config/options`. This has the advantage
of allowing users and other developers building on top of Eastwood's
REPL functionality to have easy access to a user's eastwood options.

This PR addresses https://github.com/jonase/eastwood/issues/155

### CODE REVIEW

**Comment by jafingerhut** [comment]
Thanks for the pull request.

Can you explain to me how someone would use this?  I'd like enough details, and/or an example, to add at least a few sentences worth of documentation on what this is useful for, and how a developer would us it.

**Comment by venantius** [comment]
Sure. 

This is intended to allow someone who's linting namespaces from the REPL to access the Eastwood options map without having to write code to slurp said options manually. So, let's say you're calling `eastwood.lint/lint` or `eastwood.lint/eastwood` - now instead of having to manually type in the options you want, you can do `(eastwood.lint/lint eastwood.config/options)` and it'll use the options you already have set in the `:eastwood` key of your project map, which were injected into that namespace when the REPL started.

If we wanted to, we could alter `eastwood.lint/lint`, `eastwood.lint/eastwood` to check to see if `opts` is nil and if so, to grab from `eastwood.config/options` by default, but I figured this was a safer place to start from.

**Comment by jafingerhut** [comment]
I have tried out this change, using the following steps:

+ created a branch in my repo to modify the 2 files as suggested in your pull request
+ do 'lein install', which installs a version 0.2.2-SNAPSHOT of eastwood in my local Maven repo, i.e. $HOME/.m2/repository/...
+ Edit my file $HOME/.lein/profiles.clj so that it uses eastwood version 0.2.2-SNAPSHOT
+ Change to the directory of another Leiningen project
+ run 'lein eastwood'

I get the exception shown below when following the steps above, and from trying to add debug print messages in the function eastwood.plugin/middleware, it appears to be thrown during the attempt to call leval/eval-in-project:

Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: eastwood.config/options in this context, compiling:(/private/var/folders/v5/7hpqbpk51td3v351377gl6yw0000gn/T/form-init3205382460136696906.clj:1:125)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: eastwood.config/options in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	... 21 more
Subprocess failed

**Comment by venantius** [comment]
Hey @jafingerhut - good catch, and I'm not sure how I didn't run into the failure you encountered myself. I've pushed up a new commit that changes the approach here, and I've tested it with the `0.2.2-SNAPSHOT` branch and it seems to work.

**Comment by vemv** [comment]
This PR predates Eastwood's API as a vanilla library which can be used as a non-plugin: as a deps.edn lib, as vanilla code that can be invoked from the repl (or any program, really), etc.

That newer path seems cleaner and should need no modifications in Eastwood's code - config would be, as usual, a concern of API clients, so one doesn't need a middleware to retain it.

Hope it helps!

**Comment by vemv** [comment]
Another thing that has changed in the meantime is that clj-kondo has become the de-facto standard for editor-level linting.

Personally I'm perfectly fine with that - Eastwood wasn't ever performant enough for a smooth editor integration anyway. It shines more in CI so that it's current focus - editor integrations are out of scope these days.

**Pull request closed without merging**
