### PR TITLE
Clean up callbacks

### PR DESCRIPTION
**Pull request by slipset**

### CODE REVIEW

**Comment by jafingerhut** [comment]
Looks reasonable to me.  A lot of changes there, but so far mostly looks like moving things into different namespaces, and some extra qualification of running code only when the `:debug` option is present?

I noticed something that looked new -- modifying Reflection and unboxed match warnings, maybe so that they look more like Eastwood warnings visually?  That seems useful.

Any other new functionality here?

**Comment by slipset** [comment]
Hmm, I don't think I planned to do anything with Reflection and unboxed math warnings.
I've basically, as you've seen, moved stuff around and moved the `:debug` check away from the "business-logic" and into the debug logic so that the business-logic stays more focussed.

Could you point me to where you see that I've changed the Reflection/unboxed math warnings?

**Comment by slipset** [comment]
Ah, I see where you see it.
It's just a matter of moving the code to the only place it was being used.
Also, I removed the passing of `opt` since it ended up only using `:cwd` out of the `opt` map, so I could make the args a bit more explissit.

**Comment by jafingerhut** [comment]
Makes sense.  Sorry, a lot of the parts of this code I have not looked at in several years now :)

If everything is working as expected, I see no reason not to merge in these changes.

**Pull request merged**
