### PR TITLE
Fix false positive re: protocols in unused-namespaces linter.

### LINKED ISSUE #162: :unused-namespaces false positive when implementing a protocol
Simply requiring a namespace for a protocol to be implemented in a record causes a false positive when using the :unused-namespaces linter.

```
lein eastwood '{:linters [:unused-namespaces]}' 
== Eastwood 0.2.1 Clojure 1.6.0 JVM 1.7.0_51
Directories scanned for source files:
  src test
== Linting protocol-test.foo ==
== Linting protocol-test.bar ==
Entering directory `/Users/derek/apps/protocol-test'
src/protocol_test/bar.clj:1:1: unused-namespaces: Namespace protocol-test.foo is never used in protocol-test.bar
== Warnings: 1 (not including reflection warnings)  Exceptions thrown: 0
Subprocess failed
```

bar.clj

```
(ns protocol-test.bar
  (:require [protocol-test.foo :as foo]))

(defrecord Bar [whatever]
  foo/Foo
  (foo [this] whatever))
```

foo.clj

```
(ns protocol-test.foo)

(defprotocol Foo
  (foo [this]))
```

### PR DESCRIPTION
**Pull request by dpassen**
This should fix #162. Let me know what you think.

### CODE REVIEW

**Comment by dpassen1** [comment]
Thoughts?

**Comment by jafingerhut** [comment]
Sorry for not responding sooner.  I have been pretty busy at the office the last several weeks, and haven't had much time to look at Eastwood during that time.  Hopefully I'll get a chance to look at it during the next month.

**Comment by dpassen1** [comment]
Could you possibly give a look some time soon?

**Comment by ccann** [comment]
any update on this merge? would love to re-enable unused-namespace checks

**Comment by jafingerhut** [comment]
Thanks for the patch, with unit test cases included, woohoo!  I tested it out on about 80 Clojure projects, and it eliminated at least 5 incorrect unused-namespace warnings.  There are definitely still some incorrect unused-namespace warnings that remain, but eliminating those can wait for a future enhancement.

**Pull request merged**
